# Referencia- és kiterjesztett implementáció konzisztencia-ellenőrzése

Ez a notebook a **„A Crouch-féle szimulációs prevalencia-becslés kiterjesztése folytonos időbeli modellezésre”** című szakdolgozat validációs anyaga.  
A dolgozat a Crouch-féle incidencia–túlélés alapú Monte Carlo prevalenciabecslés elméleti keretére és a meglévő `rprev` referencia-implementációra épül. A központi feladat a referencia-eljárás több indexdátum együttes kezelésére szolgáló kiterjesztése, valamint ennek módszertani és numerikus validálása (lásd: 3–5. fejezet).

Ennek megfelelően a **referencia** implementáció definíció szerint egyetlen indexdátumhoz ad prevalencia-becslést, ezért több indexdátum esetén az eredmény egyindexű `prevalence()` hívások sorozatából állítható elő. A **kiterjesztett implementáció** ezzel szemben több indexdátum együttes kezelésére készült, és a teljes indexrácsra konzisztens becslést ad egy közös futási keretben (lásd: 4. fejezet – referencia implementáció és a kiterjesztés tárgya; 5. fejezet – matematikai modell és csomagszintű illesztés).

## Validációs cél

A notebook célja annak vizsgálata, hogy a referencia implementációból indexdátumonként összeállított kimenet és a natív többindexű kiterjesztett futtatás kimenete azonos bemenetek (adat, modellek), azonos indexrács és azonos további paraméterek mellett összevethető-e, továbbá hogy a megfigyelt eltérések a kiterjesztés definiált módszertani és algoritmikus sajátosságai mellett értelmezhetők-e.

## Egyezési kritériumok és eltérésértelmezés

A két implementáció futási szerkezete eltér, ezért a véletlenszám-generátor hívásainak száma és ütemezése sem azonos (lásd dolgozat 5. fejezet). A referencia-megoldás indexdátumonként külön futtatással állít elő prevalencia-becslést, így a bináris státuszok véletlen komponense is indexdátumonként, elkülönülő Bernoulli-sorsolásokon keresztül képződik. Ezzel szemben a kiterjesztett megoldásban a státuszképzés véletlen komponense esetszinten egyetlen `xi ~ Unif(0,1)` küszöbhöz kötött, és ezt hasonlítjuk össze az indexrács pontjaihoz tartozó túlélési valószínűségekkel. A két státuszképzési szervezés különbsége miatt azonos induló véletlenmag mellett sem várható bitazonos kimenet; az összevetést a kimeneti összefoglalók (pontbecslés, intervallumhatárok) szintjén végezzük.

A referencia és a kiterjesztett implementáció kimenetét akkor tekintjük konzisztensnek, ha a relatív eltérések az indexrácson kontrolláltak. A pontbecslésre a

$$
\delta_{\widehat{P}}(t_k)
=
\frac{\widehat{P}_{\mathrm{ext}}(t_k)-\widehat{P}_{\mathrm{ref}}(t_k)}{\widehat{P}_{\mathrm{ref}}(t_k)}
$$

relatív eltérést, míg az intervallumhatárokra (minden $\alpha\in\{0.025,\,0.975\}$ esetén) a

$$
\delta_{q,\alpha}(t_k)
=
\frac{q_{\alpha,\mathrm{ext}}(t_k)-q_{\alpha,\mathrm{ref}}(t_k)}{q_{\alpha,\mathrm{ref}}(t_k)}
$$

relatív eltérést képezzük. Az egyezést a rácson vett eltérések nagyságrendje alapján értékeljük: rögzített $N_{\mathrm{boot}}=1000$ (azonosan $N_{\mathrm{sim}}=1000$) mellett akkor tekintjük teljesültnek, ha a rácson vett $|\delta_{\widehat{P}}(t_k)|$ és $|\delta_{q,\alpha}(t_k)|$ eltérések maximális értéke nem haladja meg az $\varepsilon_{\max}=10^{-2}$, és az átlagos értéke nem haladja meg az $\varepsilon_{\mathrm{mean}}=10^{-3}$ küszöböt. A maximális eltéréseket külön riportáljuk, és azok alapján ellenőrizzük, hogy a kilógó pontok nem mutatnak a teljes indexrácsot érintő, tartós mintázatot.

A konzisztencia értelmezéséhez két diagnosztikai ellenőrzést is végzünk:

- az eltérések az indexrács mentén nem mutatnak tartós, egyirányú eltolódást;

- a szimulációs ismétlésszám növelésével ($N_{\mathrm{sim}}$, illetve ahol releváns $N_{\mathrm{boot}}$) a relatív eltérések a nullához konvergálnak, vagyis az indexrácson mért $|\delta_{\widehat{P}}(t_k)|$ és $|\delta_{q,\alpha}(t_k)|$ mennyiségek rendre csökkennek.

## Notebook felépítése

1. Közös paraméterezés rögzítése.  
2. Referencia-kimenet előállítása indexdátumonkénti, egyindexű `prevalence()` hívások sorozatával.  
3. Kiterjesztett implementáció futtatása a teljes indexrácsra.  
4. Célzott összevetés a kimenetszintű mennyiségekre (pontbecslés és intervallumhatárok) az indexrácson.  
5. Konvergenciaellenőrzés: a szimulációs ismétlésszám növelésével ($N_{\mathrm{sim}}$, illetve paraméterben $N_{\mathrm{boot}}$) a referencia--kiterjesztett relatív eltérések nullához tartásának vizsgálata.

---
### 1. Közös paraméter konfiguráció
- A referencia és a kiterjesztett megoldása futtatása ugyanebből a paraméterkészletből dolgozik, így az összevetés konzisztens.

In [1]:
# Common configuration (shared across runs)
seeds <- c(20260301, 20260302, 20260303, 20260304, 20260305, 20260306, 20260307, 20260308, 20260309, 20260310)
seed <- seeds[1]
N_boot <- 1000L
num_years <- c(3, 5, 10, 13, 15, 20, 25)

# Index date grid (K = number of index dates)
K <- 3L
index_start <- as.Date("2012-01-07")
index_dates <- seq.Date(from = index_start, by = "year", length.out = K)

# Model + prevalence settings
inc_formula <- entrydate ~ sex
surv_formula <- survival::Surv(time, status) ~ age + sex
dist <- "weibull"
population_size <- 1e6
death_column <- "eventdate"
status_col <- "status"

### 2. Környezet előkészítése
- Betöltjük a szükséges csomagokat (`rprev`, `survival`, `lubridate`), valamint a `prevsim` példaadatot, hogy a referenciafuttatások egységes környezetben és bemeneten induljanak.
- A betöltött adatokból előállítjuk a futtatásokhoz használt munkatáblát (`base_df`), amelyet a későbbi összevetések során konzisztensen használunk.

In [2]:
# Csomagok betöltése
suppressPackageStartupMessages({
  library(rprev)
  library(survival)
  library(lubridate)
})

# Példaadat betöltése (kiinduló tábla)
data(prevsim, package = "rprev")
base_df <- as.data.frame(prevsim)

# Közös, futtatások között megosztott dátumparaméterek
registry_start_date <- min(base_df$entrydate, na.rm = TRUE)
registry_start_date

Warning message:
"package 'rprev' was built under R version 4.4.3"
Warning message:
"package 'lubridate' was built under R version 4.4.3"

[1] "2003-01-07"

### 3. Referencia `rprev` implementáció futtatása
- A referencia implementáció `prevalence()` függvénye egyetlen indexdátumra ad becslést. Több indexdátum esetén a viszonyítási eredmény indexdátumonként ismételt különálló futtatásokból áll elő.
- A kiértékelést több seed beállítás mellett is elvégezzük.

In [3]:
# K>1 (több indexdátum, ismételt K=1 futások)
# A registry start dátumot a környezet-előkészítő blokkban rögzítettük: `registry_start_date`

ref_abs_table_by_seed <- list()
res_ref_by_index_by_seed <- list()

# Gyors áttekintés: abszolút prevalencia indexdátumonként, horizontonként
extract_abs <- function(res) {
  out <- sapply(num_years, function(y) {
    as.numeric(res$estimates[[paste0("y", y)]][["absolute.prevalence"]])
  })
  names(out) <- paste0("y", num_years)
  out
}

# A seedek listáját a közös konfigurációban adjuk meg: `seeds`
for (s in seeds) {
  cat("\n", paste(rep("-", 80), collapse = ""), "\n", sep = "")
  cat("seed =", s, "\n")

  # Reprodukálható viszonyítás: az indexdátumonkénti referencia-futtatásokat ugyanazzal a seeddel indítjuk,
  # így a K>1 viszonyítási sorozat indexek közötti különbségeit nem a véletlenszám-hívások "elmászó" állapota,
  # hanem az eltérő indexdátumokhoz tartozó becslési helyzet magyarázza.
  res_ref_by_index_s <- lapply(index_dates, function(idx) {
    set.seed(s)
    rprev::prevalence(
      index = idx,
      num_years_to_estimate = num_years,
      data = base_df,
      inc_formula = inc_formula,
      surv_formula = surv_formula,
      dist = dist,
      population_size = population_size,
      death_column = death_column,
      registry_start_date = registry_start_date,
      N_boot = N_boot
    )
  })
  names(res_ref_by_index_s) <- as.character(index_dates)
  res_ref_by_index_by_seed[[as.character(s)]] <- res_ref_by_index_s

  ref_abs_table_s <- t(sapply(res_ref_by_index_s, extract_abs))
  ref_abs_table_by_seed[[as.character(s)]] <- ref_abs_table_s
  print(ref_abs_table_s)

  if (s == seeds[1]) {
    res_ref_by_index <- res_ref_by_index_s
    ref_abs_table <- ref_abs_table_s
  }
}

# A további összevetésekhez a `seeds[1]` futtatás eredményeit használjuk
# ref_abs_table

--------------------------------------------------------------------------------
seed = 20260301
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.35 598.35 650.83 762.57 850.63
2013-01-07 207 304 517.00 606.37 658.48 769.78 857.76
2014-01-07 127 226 433.00 530.41 582.96 694.63 782.69

--------------------------------------------------------------------------------
seed = 20260302
            y3  y5    y10   y13    y15    y20    y25
2012-01-07 207 297 508.49 598.4 650.73 762.22 850.62
2013-01-07 207 304 517.00 606.0 658.32 769.98 858.73
2014-01-07 127 226 433.00 530.3 582.69 694.12 782.52

--------------------------------------------------------------------------------
seed = 20260303
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.26 597.34 650.02 762.02 851.34
2013-01-07 207 304 517.00 606.35 658.66 770.77 860.07
2014-01-07 127 226 433.00 529.76 582.51 694.44 783.76

--------------------------------------------------------------------------------
seed = 20260304
            y3  y5   y10    y13    y15    y20    y25
2012-01-07 207 297 508.1 597.32 650.09 761.20 849.95
2013-01-07 207 304 517.0 606.36 658.96 770.27 859.16
2014-01-07 127 226 433.0 529.83 582.68 693.70 782.45

--------------------------------------------------------------------------------
seed = 20260305
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.34 597.64 649.88 762.18 850.84
2013-01-07 207 304 517.00 606.85 659.48 771.32 859.58
2014-01-07 127 226 433.00 529.92 582.24 694.46 783.12

--------------------------------------------------------------------------------
seed = 20260306
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.33 597.34 649.18 760.66 849.59
2013-01-07 207 304 517.00 606.44 658.34 770.35 858.61
2014-01-07 127 226 433.00 529.83 581.74 693.14 782.08

--------------------------------------------------------------------------------
seed = 20260307
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.58 597.38 649.50 760.81 849.34
2013-01-07 207 304 517.00 606.14 658.35 769.61 858.15
2014-01-07 127 226 433.00 529.45 581.63 692.88 781.41

--------------------------------------------------------------------------------
seed = 20260308
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.38 597.52 650.12 761.38 849.72
2013-01-07 207 304 517.00 606.72 659.25 770.71 859.17
2014-01-07 127 226 433.00 529.80 582.48 693.66 782.00

--------------------------------------------------------------------------------
seed = 20260309
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.35 597.97 650.86 762.57 851.33
2013-01-07 207 304 517.00 606.32 658.59 770.12 858.98
2014-01-07 127 226 433.00 530.10 583.06 694.70 783.46

--------------------------------------------------------------------------------
seed = 20260310
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.34 597.65 650.34 763.02 851.82
2013-01-07 207 304 517.00 606.27 658.70 771.17 860.17
2014-01-07 127 226 433.00 529.87 582.62 695.24 784.04

### 4. Kiterjesztett rprev csomag betöltése lokális forrásból és git-meta rögzítése
- A csomag lokális forrásból kerül betöltésre, így a futtatás ténylegesen a vizsgált, módosított implementációval történik.
- A futtatott verzió azonosíthatóságát a git ág és commit azonosító kiírása biztosítja.

In [4]:
# Projekt lokális gyökérkönyvtárának meghatározása (git repo root)
project_root <- trimws(system2("git", c("rev-parse", "--show-toplevel"), stdout = TRUE))
if (length(project_root) == 0 || !dir.exists(project_root)) {
  stop("Could not resolve project root from git.")
}

# Telepített rprev leválasztása, majd lokális forrásból betöltés
if ("package:rprev" %in% search()) detach("package:rprev", unload = TRUE, character.only = TRUE)
if ("rprev" %in% loadedNamespaces()) unloadNamespace("rprev")
if (!requireNamespace("devtools", quietly = TRUE)) stop("devtools package is not available.")

suppressPackageStartupMessages(devtools::load_all(project_root, quiet = TRUE))

# Betöltött csomag elérési útjának megjelenítése
cat(
  "Loaded rprev from: ",
  # normalizePath(getNamespaceInfo("rprev", "path"), winslash = "/"),
  # "\n",
  sep = ""
)

Warning message:
"package 'testthat' was built under R version 4.4.3"

Loaded rprev from:

In [5]:
# Git meta rögzítése: futtatott kódverzió azonosítása
git_cmd <- function(args) {
  out <- suppressWarnings(
    tryCatch(system2("git", args, stdout = TRUE, stderr = TRUE), error = function(e) character(0))
  )
  status <- attr(out, "status")
  if (!is.null(status) || length(out) == 0) return(NA_character_)
  trimws(out[[1]])
}

old_wd <- getwd()                         # munkakönyvtár mentése
on.exit(setwd(old_wd), add = TRUE)        # visszaállítás a cella végén
setwd(project_root)                       # git parancsok futtatása a repo gyökeréből

branch <- git_cmd(c("rev-parse", "--abbrev-ref", "HEAD"))
commit <- git_cmd(c("rev-parse", "HEAD"))

cat("Git branch: ", branch, "\n", sep = "")
cat("Git commit: ", commit, "\n", sep = "")

Git branch: notebooks/ref-ext-consistency
Git commit: b567147a198e288fd283932d0ab474b439c39d48

### 5. Kiterjesztett `rprev` implementáció futtatása
- Az előző blokkban betöltött lokális implementáció `prevalence()` függvényének futtatása ugyanazzal az indexdátum- és paraméterkészlettel, mint a referenciafuttatásoknál.
- A kiértékelést több seed beállítás mellett is elvégezzük.

In [6]:
years_lbl <- paste0("y", num_years)

ext_abs_table_by_seed <- list()
res_ext_kmulti_by_seed <- list()

# A seedek listáját a közös konfigurációban adjuk meg: `seeds`
for (s in seeds) {
  cat("\n", paste(rep("-", 80), collapse = ""), "\n", sep = "")
  cat("seed =", s, "\n")

  set.seed(s)
  res_ext_kmulti_s <- prevalence(
    index = index_dates,
    num_years_to_estimate = num_years,
    data = base_df,
    inc_formula = inc_formula,
    surv_formula = surv_formula,
    dist = dist,
    population_size = population_size,
    death_column = death_column,
    registry_start_date = registry_start_date,
    N_boot = N_boot
  )
  print(summary(res_ext_kmulti_s))
  res_ext_kmulti_by_seed[[as.character(s)]] <- res_ext_kmulti_s

  ext_abs_table_s <- do.call(
    cbind,
    lapply(num_years, function(y) {
      est <- res_ext_kmulti_s$estimates[[paste0("y", y)]]
      est <- est[order(est$index_date), , drop = FALSE]
      as.numeric(est[["absolute.prevalence"]])
    })
  )
  colnames(ext_abs_table_s) <- years_lbl
  rownames(ext_abs_table_s) <- as.character(sort(unique(res_ext_kmulti_s$index_dates)))
  ext_abs_table_by_seed[[as.character(s)]] <- ext_abs_table_s
  print(ext_abs_table_s)

  if (s == seeds[1]) {
    res_ext_kmulti <- res_ext_kmulti_s
    ext_abs_table <- ext_abs_table_s
  }
}

# A további összevetésekhez a `seeds[1]` futtatás eredményeit használjuk
# ext_abs_table

--------------------------------------------------------------------------------
seed = 20260301
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.03   50.80         56.20         45.41
 2012-01-07    13              597.82   59.78         66.64         52.93
 2012-01-07    15              650.47   65.05         72.65         57.44
 2012-01-07    20              762.66   76.27         85.56         66.97
 2012-01-07    25              851.23   85.12         95.92         74.33
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.39   60.64         67.20         54.08
 2013-01-07    15              658.77   65.88         73.24         58.52
 2013-01-07    20              771.05   77.11         86.26         67.95
 2013-01-07    25              859.83   85.98         96.58         75.38
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              529.93   52.99         58.87         47.11
 2014-01-07    15              582.46   58.25         64.99         51.50
 2014-01-07    20              694.51   69.45         78.02         60.88
 2014-01-07    25              783.17   78.32         88.36         68.27

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6004299
 2013-01-07 0.4310471
 2014-01-07 0.1128965
           index_date      pval
2012-01-07 2012-01-07 0.6004299
2013-01-07 2013-01-07 0.4310471
2014-01-07 2014-01-07 0.1128965
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.03 597.82 650.47 762.66 851.23
2013-01-07 207 304 517.00 606.39 658.77 771.05 859.83
2014-01-07 127 226 433.00 529.93 582.46 694.51 783.17

--------------------------------------------------------------------------------
seed = 20260302
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.34   50.83         56.28         45.39
 2012-01-07    13              597.94   59.79         66.63         52.96
 2012-01-07    15              650.40   65.04         72.65         57.43
 2012-01-07    20              762.33   76.23         85.48         66.98
 2012-01-07    25              851.55   85.16         95.95         74.36
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.78   60.68         67.30         54.06
 2013-01-07    15              659.01   65.90         73.29         58.51
 2013-01-07    20              771.23   77.12         86.20         68.05
 2013-01-07    25              860.29   86.03         96.69         75.37
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              530.04   53.00         58.89         47.12
 2014-01-07    15              582.81   58.28         65.05         51.51
 2014-01-07    20              695.24   69.52         78.05         61.00
 2014-01-07    25              784.15   78.41         88.50         68.33

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6235809
 2013-01-07 0.4499326
 2014-01-07 0.1060479
           index_date      pval
2012-01-07 2012-01-07 0.6235809
2013-01-07 2013-01-07 0.4499326
2014-01-07 2014-01-07 0.1060479
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.34 597.94 650.40 762.33 851.55
2013-01-07 207 304 517.00 606.78 659.01 771.23 860.29
2014-01-07 127 226 433.00 530.04 582.81 695.24 784.15

--------------------------------------------------------------------------------
seed = 20260303
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.21   50.82         56.24         45.41
 2012-01-07    13              597.24   59.72         66.62         52.82
 2012-01-07    15              649.48   64.95         72.59         57.31
 2012-01-07    20              760.38   76.04         85.25         66.82
 2012-01-07    25              848.81   84.88         95.62         74.14
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.23   60.62         67.25         53.99
 2013-01-07    15              658.36   65.84         73.20         58.47
 2013-01-07    20              769.33   76.93         85.93         67.93
 2013-01-07    25              857.52   85.75         96.25         75.26
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              529.73   52.97         58.88         47.06
 2014-01-07    15              582.22   58.22         64.98         51.47
 2014-01-07    20              693.29   69.33         77.78         60.87
 2014-01-07    25              781.10   78.11         88.03         68.19

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.5776510
 2013-01-07 0.4126112
 2014-01-07 0.1276580
           index_date      pval
2012-01-07 2012-01-07 0.5776510
2013-01-07 2013-01-07 0.4126112
2014-01-07 2014-01-07 0.1276580
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.21 597.24 649.48 760.38 848.81
2013-01-07 207 304 517.00 606.23 658.36 769.33 857.52
2014-01-07 127 226 433.00 529.73 582.22 693.29 781.10

--------------------------------------------------------------------------------
seed = 20260304
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.06   50.81         56.28         45.33
 2012-01-07    13              597.88   59.79         66.71         52.87
 2012-01-07    15              650.34   65.03         72.57         57.50
 2012-01-07    20              761.30   76.13         85.44         66.81
 2012-01-07    25              849.76   84.98         95.76         74.19
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.42   60.64         67.21         54.08
 2013-01-07    15              659.22   65.92         73.26         58.59
 2013-01-07    20              770.19   77.02         86.09         67.94
 2013-01-07    25              858.70   85.87         96.44         75.30
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              529.86   52.99         58.91         47.07
 2014-01-07    15              582.57   58.26         65.06         51.45
 2014-01-07    20              693.54   69.35         77.84         60.86
 2014-01-07    25              782.18   78.22         88.24         68.20

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6004299
 2013-01-07 0.4310471
 2014-01-07 0.1128965
           index_date      pval
2012-01-07 2012-01-07 0.6004299
2013-01-07 2013-01-07 0.4310471
2014-01-07 2014-01-07 0.1128965
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.06 597.88 650.34 761.30 849.76
2013-01-07 207 304 517.00 606.42 659.22 770.19 858.70
2014-01-07 127 226 433.00 529.86 582.57 693.54 782.18

--------------------------------------------------------------------------------
seed = 20260305
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.34   50.83         56.30         45.37
 2012-01-07    13              597.69   59.77         66.56         52.97
 2012-01-07    15              650.17   65.02         72.49         57.54
 2012-01-07    20              761.36   76.14         85.13         67.14
 2012-01-07    25              849.31   84.93         95.29         74.57
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.74   60.67         67.20         54.15
 2013-01-07    15              658.96   65.90         73.15         58.64
 2013-01-07    20              770.15   77.02         85.85         68.18
 2013-01-07    25              858.26   85.83         96.01         75.64
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              530.10   53.01         58.87         47.15
 2014-01-07    15              582.35   58.23         64.90         51.57
 2014-01-07    20              693.70   69.37         77.67         61.07
 2014-01-07    25              781.93   78.19         87.85         68.53

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6004299
 2013-01-07 0.4499326
 2014-01-07 0.1128965
           index_date      pval
2012-01-07 2012-01-07 0.6004299
2013-01-07 2013-01-07 0.4499326
2014-01-07 2014-01-07 0.1128965
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.34 597.69 650.17 761.36 849.31
2013-01-07 207 304 517.00 606.74 658.96 770.15 858.26
2014-01-07 127 226 433.00 530.10 582.35 693.70 781.93

--------------------------------------------------------------------------------
seed = 20260306
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.28   50.83         56.28         45.37
 2012-01-07    13              598.25   59.82         66.61         53.04
 2012-01-07    15              650.84   65.08         72.55         57.62
 2012-01-07    20              762.48   76.25         85.38         67.11
 2012-01-07    25              850.73   85.07         95.69         74.46
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.83   60.68         67.19         54.18
 2013-01-07    15              659.28   65.93         73.19         58.67
 2013-01-07    20              771.14   77.11         86.08         68.15
 2013-01-07    25              859.54   85.95         96.43         75.47
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              530.10   53.01         58.87         47.15
 2014-01-07    15              582.73   58.27         64.97         51.58
 2014-01-07    20              694.56   69.46         77.87         61.04
 2014-01-07    25              782.88   78.29         88.21         68.36

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6004299
 2013-01-07 0.4499326
 2014-01-07 0.1200962
           index_date      pval
2012-01-07 2012-01-07 0.6004299
2013-01-07 2013-01-07 0.4499326
2014-01-07 2014-01-07 0.1200962
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.28 598.25 650.84 762.48 850.73
2013-01-07 207 304 517.00 606.83 659.28 771.14 859.54
2014-01-07 127 226 433.00 530.10 582.73 694.56 782.88

--------------------------------------------------------------------------------
seed = 20260307
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.64   50.86         56.32         45.41
 2012-01-07    13              597.55   59.75         66.58         52.93
 2012-01-07    15              649.66   64.97         72.48         57.45
 2012-01-07    20              761.43   76.14         85.33         66.95
 2012-01-07    25              849.66   84.97         95.74         74.20
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.54   60.65         67.31         54.00
 2013-01-07    15              658.43   65.84         73.18         58.50
 2013-01-07    20              770.01   77.00         86.01         68.00
 2013-01-07    25              858.11   85.81         96.42         75.20
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              530.12   53.01         58.95         47.07
 2014-01-07    15              582.20   58.22         64.97         51.47
 2014-01-07    20              693.71   69.37         77.80         60.94
 2014-01-07    25              781.92   78.19         88.22         68.17

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.5776510
 2013-01-07 0.4310471
 2014-01-07 0.1128965
           index_date      pval
2012-01-07 2012-01-07 0.5776510
2013-01-07 2013-01-07 0.4310471
2014-01-07 2014-01-07 0.1128965
            y3  y5    y10    y13    y15    y20    y25
2012-01-07 207 297 508.64 597.55 649.66 761.43 849.66
2013-01-07 207 304 517.00 606.54 658.43 770.01 858.11
2014-01-07 127 226 433.00 530.12 582.20 693.71 781.92

--------------------------------------------------------------------------------
seed = 20260308
Prevalence
~~~~~~~~~~
Estimated prevalence:
 index_date years absolute.prevalence per100K per100K.upper per100K.lower
 2012-01-07     3              207.00   20.70         23.52         17.88
 2012-01-07     5              297.00   29.70         33.08         26.32
 2012-01-07    10              508.14   50.81         56.31         45.32
 2012-01-07    13              597.39   59.74         66.66         52.81
 2012-01-07    15              649.84   64.98         72.66         57.31
 2012-01-07    20              761.34   76.13         85.39         66.88
 2012-01-07    25              850.36   85.04         95.78         74.29
 2013-01-07     3              207.00   20.70         23.52         17.88
 2013-01-07     5              304.00   30.40         33.82         26.98
 2013-01-07    10              517.00   51.70         56.16         47.24
 2013-01-07    13              606.40   60.64         67.30         53.98
 2013-01-07    15              658.66   65.87         73.26         58.48
 2013-01-07    20              770.11   77.01         86.02         68.00
 2013-01-07    25              858.96   85.90         96.44         75.35
 2014-01-07     3              127.00   12.70         14.91         10.49
 2014-01-07     5              226.00   22.60         25.55         19.65
 2014-01-07    10              433.00   43.30         47.38         39.22
 2014-01-07    13              530.03   53.00         58.93         47.08
 2014-01-07    15              582.16   58.22         65.03         51.40
 2014-01-07    20              693.71   69.37         77.82         60.92
 2014-01-07    25              782.50   78.25         88.20         68.30

Registry Data
~~~~~~~~~~~~~
Index date(s): 2012-01-07, 2013-01-07, 2014-01-07
Start date: 2003-01-07
Overall incidence rate: 0.249
Counted prevalent cases:
 index_date counted
 2012-01-07     475
 2013-01-07     517
 2014-01-07     472

Simulation
~~~~~~~~~~
Iterations: 1000
Average incidence rate: 0.295
P-values:
 index_date      pval
 2012-01-07 0.6004299
 2013-01-07 0.4310471
 2014-01-07 0.1128965
           index_date      pval
2012-01-07 2012-01-07 0.6004299
2013-01-07 2013-01-07 0.4310471
2014-01-07 2014-01-07 0.1128965
            y3  y5    y10    y13    y15    y20    y25

### 6. Eredmények összehasonlítása (referencia vs kiterjesztett)
- Az alábbi táblázat az abszolút prevalencia-becsléseket veti össze indexdátumonként és időhorizontonként.
- A `counted` oszlop a regiszterből közvetlenül számlált prevalens esetszámot mutatja (indexdátumonként), a `ref` és `ext` oszlopok pedig az eljárások becsléseit.
- A `delta` oszlop a két becslés különbsége: `delta = kiterjesztett - referencia`.
- A relatív eltérést a `delta_rel = (ext - ref) / ref` és `abs_delta_rel = |delta_rel|` oszlopok adják.
- A `eps_ok_max` és `eps_ok_mean` jelzi, hogy az adott rácsponton `abs_delta_rel` rendre `1e-2`, illetve `1e-3` alatt marad-e.

In [7]:
# Dinamikus összevetés: referencia (ismételt K=1) vs kiterjesztett (natív többindexű), seed szerint

counted_by_date <- sapply(res_ref_by_index, function(res) as.numeric(res$counted))
names(counted_by_date) <- names(res_ref_by_index)

epsilon_max <- 1e-2
epsilon_mean <- 1e-3

build_compare_df <- function(ref_mat, ext_mat) {
  idx <- intersect(rownames(ref_mat), rownames(ext_mat))
  yrs <- intersect(colnames(ref_mat), colnames(ext_mat))

  df <- expand.grid(index_date = idx, horizon = yrs, stringsAsFactors = FALSE)
  df$ref <- mapply(function(r, c) as.numeric(ref_mat[r, c]), df$index_date, df$horizon)
  df$ext <- mapply(function(r, c) as.numeric(ext_mat[r, c]), df$index_date, df$horizon)

  counted_i <- counted_by_date[as.character(idx)]
  df$counted <- as.numeric(counted_i[df$index_date])

  df$delta <- df$ext - df$ref
  df$delta_rel <- ifelse(df$ref == 0, NA_real_, df$delta / df$ref)
  df$abs_delta_rel <- abs(df$delta_rel)
  df$eps_ok_max <- df$abs_delta_rel <= epsilon_max
  df$eps_ok_mean <- df$abs_delta_rel <= epsilon_mean

  df$horizon_years <- as.integer(sub("^y", "", df$horizon))
  idx_d <- as.Date(df$index_date)
  start_d <- idx_d - round(df$horizon_years * 365.25)
  yrs_need <- as.numeric(difftime(registry_start_date, start_d, units = "days")) / 365.25
  df$sim_inc_years <- as.integer(round(pmax(0, pmin(df$horizon_years, yrs_need))))
  df <- df[order(as.Date(df$index_date), df$horizon_years), ]
  df$horizon <- NULL
  df <- df[, c("index_date", "horizon_years", "sim_inc_years", "counted", "ref", "ext", "delta", "delta_rel", "abs_delta_rel", "eps_ok_max", "eps_ok_mean")]

  df$ref <- round(df$ref, 2)
  df$ext <- round(df$ext, 2)
  df$delta <- round(df$delta, 2)
  df$delta_rel <- round(df$delta_rel, 6)
  df$abs_delta_rel <- round(df$abs_delta_rel, 6)

  df
}

compare_list <- lapply(seeds, function(s) {
  ref_mat <- ref_abs_table_by_seed[[as.character(s)]]
  ext_mat <- ext_abs_table_by_seed[[as.character(s)]]
  df <- build_compare_df(ref_mat, ext_mat)
  df$seed <- s
  df
})

compare_all <- data.table::rbindlist(compare_list, fill = TRUE)
compare_all <- compare_all[order(compare_all$seed, as.Date(compare_all$index_date), compare_all$horizon_years), ]
compare_all <- compare_all[, c("seed", "index_date", "horizon_years", "sim_inc_years", "counted", "ref", "ext", "delta", "delta_rel", "abs_delta_rel", "eps_ok_max", "eps_ok_mean")]

compare_all

    seed     index_date horizon_years sim_inc_years counted ref    ext    delta
1   20260301 2012-01-07  3             0            475     207.00 207.00  0.00
2   20260301 2012-01-07  5             0            475     297.00 297.00  0.00
3   20260301 2012-01-07 10             1            475     508.35 508.03 -0.32
4   20260301 2012-01-07 13             4            475     598.35 597.82 -0.53
5   20260301 2012-01-07 15             6            475     650.83 650.47 -0.36
6   20260301 2012-01-07 20            11            475     762.57 762.66  0.09
7   20260301 2012-01-07 25            16            475     850.63 851.23  0.60
8   20260301 2013-01-07  3             0            517     207.00 207.00  0.00
9   20260301 2013-01-07  5             0            517     304.00 304.00  0.00
10  20260301 2013-01-07 10             0            517     517.00 517.00  0.00
11  20260301 2013-01-07 13             3            517     606.37 606.39  0.02
12  20260301 2013-01-07 15             5            517     658.48 658.77  0.29
13  20260301 2013-01-07 20            10            517     769.78 771.05  1.27
14  20260301 2013-01-07 25            15            517     857.76 859.83  2.07
15  20260301 2014-01-07  3             0            472     127.00 127.00  0.00
16  20260301 2014-01-07  5             0            472     226.00 226.00  0.00
17  20260301 2014-01-07 10             0            472     433.00 433.00  0.00
18  20260301 2014-01-07 13             2            472     530.41 529.93 -0.48
19  20260301 2014-01-07 15             4            472     582.96 582.46 -0.50
20  20260301 2014-01-07 20             9            472     694.63 694.51 -0.12
21  20260301 2014-01-07 25            14            472     782.69 783.17  0.48
22  20260302 2012-01-07  3             0            475     207.00 207.00  0.00
23  20260302 2012-01-07  5             0            475     297.00 297.00  0.00
24  20260302 2012-01-07 10             1            475     508.49 508.34 -0.15
25  20260302 2012-01-07 13             4            475     598.40 597.94 -0.46
26  20260302 2012-01-07 15             6            475     650.73 650.40 -0.33
27  20260302 2012-01-07 20            11            475     762.22 762.33  0.11
28  20260302 2012-01-07 25            16            475     850.62 851.55  0.93
29  20260302 2013-01-07  3             0            517     207.00 207.00  0.00
30  20260302 2013-01-07  5             0            517     304.00 304.00  0.00
⋮   ⋮        ⋮          ⋮             ⋮             ⋮       ⋮      ⋮      ⋮
181 20260309 2013-01-07 20            10            517     770.12 770.62  0.50
182 20260309 2013-01-07 25            15            517     858.98 858.89 -0.09
183 20260309 2014-01-07  3             0            472     127.00 127.00  0.00
184 20260309 2014-01-07  5             0            472     226.00 226.00  0.00
185 20260309 2014-01-07 10             0            472     433.00 433.00  0.00
186 20260309 2014-01-07 13             2            472     530.10 530.01 -0.09
187 20260309 2014-01-07 15             4            472     583.06 582.70 -0.36
188 20260309 2014-01-07 20             9            472     694.70 694.29 -0.41
189 20260309 2014-01-07 25            14            472     783.46 782.39 -1.07
190 20260310 2012-01-07  3             0            475     207.00 207.00  0.00
191 20260310 2012-01-07  5             0            475     297.00 297.00  0.00
192 20260310 2012-01-07 10             1            475     508.34 508.58  0.24
193 20260310 2012-01-07 13             4            475     597.65 598.38  0.73
194 20260310 2012-01-07 15             6            475     650.34 651.19  0.85
195 20260310 2012-01-07 20            11            475     763.02 763.94  0.92
196 20260310 2012-01-07 25            16            475     851.82 852.79  0.97
197 20260310 2013-01-07  3             0            517     207.00 207.00  0.00
198 20260310 2013-01-07  5             0            517     304.00 304.00  0.00
199 20260310 2013-01-07 10             0            517     517.00 517.00  0.00
200 20260310 2013-01-07 13             3            517     606.27 607.16  0.89
201 20260310 2013-01-07 15             5            517     658.70 659.83  1.13
202 20260310 2013-01-07 20            10            517     771.17 772.41  1.24
203 20260310 2013-01-07 25            15            517     860.17 861.60  1.43
204 20260310 2014-01-07  3             0            472     127.00 127.00  0.00
205 20260310 2014-01-07  5             0            472     226.00 226.00  0.00
206 20260310 2014-01-07 10             0            472     433.00 433.00  0.00
207 20260310 2014-01-07 13             2            472     529.87 530.43  0.56
208 20260310 2014-01-07 15             4            472     582.62 583.23  0.61
209 20260310 2014-01-07 20             9            472     695.24 695.69  0.45
210 20260310 2014-01-07 25            14            472     784.04 785.24  1.20
    delta_rel abs_delta_rel eps_ok_max eps_ok_mean
1    0.000000 0.000000      TRUE        TRUE
2    0.000000 0.000000      TRUE        TRUE
3   -0.000629 0.000629      TRUE        TRUE
4   -0.000886 0.000886      TRUE        TRUE
5   -0.000553 0.000553      TRUE        TRUE
6    0.000118 0.000118      TRUE        TRUE
7    0.000705 0.000705      TRUE        TRUE
8    0.000000 0.000000      TRUE        TRUE
9    0.000000 0.000000      TRUE        TRUE
10   0.000000 0.000000      TRUE        TRUE
11   0.000033 0.000033      TRUE        TRUE
12   0.000440 0.000440      TRUE        TRUE
13   0.001650 0.001650      TRUE       FALSE
14   0.002413 0.002413      TRUE       FALSE
15   0.000000 0.000000      TRUE        TRUE
16   0.000000 0.000000      TRUE        TRUE
17   0.000000 0.000000      TRUE        TRUE
18  -0.000905 0.000905      TRUE        TRUE
19  -0.000858 0.000858      TRUE        TRUE
20  -0.000173 0.000173      TRUE        TRUE
21   0.000613 0.000613      TRUE        TRUE
22   0.000000 0.000000      TRUE        TRUE
23   0.000000 0.000000      TRUE        TRUE
24  -0.000295 0.000295      TRUE        TRUE
25  -0.000769 0.000769      TRUE        TRUE
26  -0.000507 0.000507      TRUE        TRUE
27   0.000144 0.000144      TRUE        TRUE
28   0.001093 0.001093      TRUE       FALSE
29   0.000000 0.000000      TRUE        TRUE
30   0.000000 0.000000      TRUE        TRUE
⋮   ⋮         ⋮             ⋮          ⋮
181  0.000649 0.000649      TRUE        TRUE
182 -0.000105 0.000105      TRUE        TRUE
183  0.000000 0.000000      TRUE        TRUE
184  0.000000 0.000000      TRUE        TRUE
185  0.000000 0.000000      TRUE        TRUE
186 -0.000170 0.000170      TRUE        TRUE
187 -0.000617 0.000617      TRUE        TRUE
188 -0.000590 0.000590      TRUE        TRUE
189 -0.001366 0.001366      TRUE       FALSE
190  0.000000 0.000000      TRUE        TRUE
191  0.000000 0.000000      TRUE        TRUE
192  0.000472 0.000472      TRUE        TRUE
193  0.001221 0.001221      TRUE       FALSE
194  0.001307 0.001307      TRUE       FALSE
195  0.001206 0.001206      TRUE       FALSE
196  0.001139 0.001139      TRUE       FALSE
197  0.000000 0.000000      TRUE        TRUE
198  0.000000 0.000000      TRUE        TRUE
199  0.000000 0.000000      TRUE        TRUE
200  0.001468 0.001468      TRUE       FALSE
201  0.001716 0.001716      TRUE       FALSE
202  0.001608 0.001608      TRUE       FALSE
203  0.001662 0.001662      TRUE       FALSE
204  0.000000 0.000000      TRUE        TRUE
205  0.000000 0.000000      TRUE        TRUE
206  0.000000 0.000000      TRUE        TRUE
207  0.001057 0.001057      TRUE       FALSE
208  0.001047 0.001047      TRUE       FALSE
209  0.000647 0.000647      TRUE        TRUE
210  0.001531 0.001531      TRUE       FALSE

#### 7. Konfidencia-intervallumok összevetése (referencia vs kiterjesztett)
- A pontbecslések mellett a prevalencia-arányra számított konfidencia-intervallumok alsó és felső határát is összevetjük a két megoldás között.
- A relatív eltérést külön képezzük az alsó és a felső határra: `delta_rel = (q_ext - q_ref) / q_ref`, illetve `abs_delta_rel = |delta_rel|`.
- Az `eps_ok_max_*` és `eps_ok_mean_*` jelzi, hogy az adott rácsponton `abs_delta_rel` rendre `1e-2`, illetve `1e-3` alatt marad-e (külön az alsó és külön a felső határra).

In [8]:
# Konfidencia-intervallumok (alsó/felső) összevetése a korábbi futások eredményeiből

stopifnot(exists("res_ref_by_index_by_seed"), exists("res_ext_kmulti_by_seed"))

get_ci_cols <- function(nms) {
  lower <- grep("^per.*\\.lower$", nms, value = TRUE)
  upper <- grep("^per.*\\.upper$", nms, value = TRUE)
  stopifnot(length(lower) >= 1, length(upper) >= 1)
  list(lower = lower[[1]], upper = upper[[1]])
}

parse_denom_from_per <- function(per_lab) {
  # pl. per100K -> 100000, per1M -> 1000000
  x <- sub("^per", "", per_lab)
  m <- regexec("^([0-9]+(?:\\.[0-9]+)?)([KM]?)$", x)
  g <- regmatches(x, m)[[1]]
  stopifnot(length(g) > 0)
  val <- as.numeric(g[2])
  unit <- g[3]
  mult <- if (unit == "K") 1e3 else if (unit == "M") 1e6 else 1
  val * mult
}

to_abs <- function(rate, denom, pop) {
  as.numeric(rate) / as.numeric(denom) * as.numeric(pop)
}

extract_ref_ci_mat <- function(res_ref_by_index_s, ci_col, denom) {
  mat <- t(sapply(res_ref_by_index_s, function(res) {
    sapply(num_years, function(y) {
      est <- res$estimates[[paste0("y", y)]]
      to_abs(est[[ci_col]], denom, population_size)
    })
  }))
  colnames(mat) <- paste0("y", num_years)
  mat
}

extract_ext_ci_mat <- function(res_ext_kmulti_s, ci_col, denom) {
  mat <- do.call(cbind, lapply(num_years, function(y) {
    est <- res_ext_kmulti_s$estimates[[paste0("y", y)]]
    est <- est[order(est$index_date), , drop = FALSE]
    to_abs(est[[ci_col]], denom, population_size)
  }))
  colnames(mat) <- paste0("y", num_years)
  rownames(mat) <- as.character(sort(unique(res_ext_kmulti_s$index_dates)))
  mat
}

build_compare_ci_df <- function(ref_lower, ref_upper, ext_lower, ext_upper) {
  idx <- intersect(rownames(ref_lower), rownames(ext_lower))
  yrs <- intersect(colnames(ref_lower), colnames(ext_lower))

  df <- expand.grid(index_date = idx, horizon = yrs, stringsAsFactors = FALSE)
  df$ref_lower <- mapply(function(r, c) as.numeric(ref_lower[r, c]), df$index_date, df$horizon)
  df$ext_lower <- mapply(function(r, c) as.numeric(ext_lower[r, c]), df$index_date, df$horizon)
  df$ref_upper <- mapply(function(r, c) as.numeric(ref_upper[r, c]), df$index_date, df$horizon)
  df$ext_upper <- mapply(function(r, c) as.numeric(ext_upper[r, c]), df$index_date, df$horizon)

  df$delta_lower <- df$ext_lower - df$ref_lower
  df$delta_upper <- df$ext_upper - df$ref_upper

  df$delta_rel_lower <- ifelse(df$ref_lower == 0, NA_real_, df$delta_lower / df$ref_lower)
  df$delta_rel_upper <- ifelse(df$ref_upper == 0, NA_real_, df$delta_upper / df$ref_upper)

  df$abs_delta_rel_lower <- abs(df$delta_rel_lower)
  df$abs_delta_rel_upper <- abs(df$delta_rel_upper)


  df$horizon_years <- as.integer(sub("^y", "", df$horizon))
  idx_d <- as.Date(df$index_date)
  start_d <- idx_d - round(df$horizon_years * 365.25)
  yrs_need <- as.numeric(difftime(registry_start_date, start_d, units = "days")) / 365.25
  df$sim_inc_years <- as.integer(round(pmax(0, pmin(df$horizon_years, yrs_need))))
  df <- df[order(as.Date(df$index_date), df$horizon_years), ]
  df$horizon <- NULL

  df <- df[, c(
    "index_date", "horizon_years", "sim_inc_years",
    "ref_lower", "ext_lower", "delta_lower", "delta_rel_lower", "abs_delta_rel_lower",
    "ref_upper", "ext_upper", "delta_upper", "delta_rel_upper", "abs_delta_rel_upper"
  )]

  df$ref_lower <- round(df$ref_lower, 2)
  df$ext_lower <- round(df$ext_lower, 2)
  df$delta_lower <- round(df$delta_lower, 2)
  df$delta_rel_lower <- round(df$delta_rel_lower, 6)
  df$abs_delta_rel_lower <- round(df$abs_delta_rel_lower, 6)

  df$ref_upper <- round(df$ref_upper, 2)
  df$ext_upper <- round(df$ext_upper, 2)
  df$delta_upper <- round(df$delta_upper, 2)
  df$delta_rel_upper <- round(df$delta_rel_upper, 6)
  df$abs_delta_rel_upper <- round(df$abs_delta_rel_upper, 6)
  df$sim_inc_years <- as.integer(df$sim_inc_years)

  data.table::as.data.table(df)
}

compare_ci_by_seed <- lapply(seeds, function(s) {
  res_ref_by_index_s <- res_ref_by_index_by_seed[[as.character(s)]]
  res_ext_kmulti_s <- res_ext_kmulti_by_seed[[as.character(s)]]

  # CI oszlopnév + denominátor a referencia-kimenetből
  y0 <- num_years[[1]]
  est0 <- res_ref_by_index_s[[1]]$estimates[[paste0("y", y0)]]
  ci_cols <- get_ci_cols(names(est0))
  per_lab <- sub("\\.lower$", "", ci_cols$lower)
  denom <- parse_denom_from_per(per_lab)

  ref_lower <- extract_ref_ci_mat(res_ref_by_index_s, ci_cols$lower, denom)
  ref_upper <- extract_ref_ci_mat(res_ref_by_index_s, ci_cols$upper, denom)

  ext_lower <- extract_ext_ci_mat(res_ext_kmulti_s, ci_cols$lower, denom)
  ext_upper <- extract_ext_ci_mat(res_ext_kmulti_s, ci_cols$upper, denom)

  out <- build_compare_ci_df(ref_lower, ref_upper, ext_lower, ext_upper)
  out[, seed := s]
  out <- out[, c("seed", setdiff(names(out), "seed")), with = FALSE]
  out
})

compare_ci_all <- data.table::rbindlist(compare_ci_by_seed, use.names = TRUE, fill = TRUE)
compare_ci_all

    seed     index_date horizon_years sim_inc_years ref_lower ext_lower
1   20260301 2012-01-07  3             0            178.8     178.8
2   20260301 2012-01-07  5             0            263.2     263.2
3   20260301 2012-01-07 10             1            454.1     454.1
4   20260301 2012-01-07 13             4            529.9     529.3
5   20260301 2012-01-07 15             6            574.6     574.4
6   20260301 2012-01-07 20            11            670.9     669.7
7   20260301 2012-01-07 25            16            742.9     743.3
8   20260301 2013-01-07  3             0            178.8     178.8
9   20260301 2013-01-07  5             0            269.8     269.8
10  20260301 2013-01-07 10             0            472.4     472.4
11  20260301 2013-01-07 13             3            540.6     540.8
12  20260301 2013-01-07 15             5            584.8     585.2
13  20260301 2013-01-07 20            10            679.5     679.5
14  20260301 2013-01-07 25            15            751.7     753.8
15  20260301 2014-01-07  3             0            104.9     104.9
16  20260301 2014-01-07  5             0            196.5     196.5
17  20260301 2014-01-07 10             0            392.2     392.2
18  20260301 2014-01-07 13             2            471.6     471.1
19  20260301 2014-01-07 15             4            515.7     515.0
20  20260301 2014-01-07 20             9            611.2     608.8
21  20260301 2014-01-07 25            14            683.4     682.7
22  20260302 2012-01-07  3             0            178.8     178.8
23  20260302 2012-01-07  5             0            263.2     263.2
24  20260302 2012-01-07 10             1            454.3     453.9
25  20260302 2012-01-07 13             4            530.1     529.6
26  20260302 2012-01-07 15             6            574.0     574.3
27  20260302 2012-01-07 20            11            669.2     669.8
28  20260302 2012-01-07 25            16            742.4     743.6
29  20260302 2013-01-07  3             0            178.8     178.8
30  20260302 2013-01-07  5             0            269.8     269.8
⋮   ⋮        ⋮          ⋮             ⋮             ⋮         ⋮
181 20260309 2013-01-07 20            10            680.3     680.7
182 20260309 2013-01-07 25            15            753.8     753.3
183 20260309 2014-01-07  3             0            104.9     104.9
184 20260309 2014-01-07  5             0            196.5     196.5
185 20260309 2014-01-07 10             0            392.2     392.2
186 20260309 2014-01-07 13             2            472.2     471.2
187 20260309 2014-01-07 15             4            516.6     516.2
188 20260309 2014-01-07 20             9            609.6     610.2
189 20260309 2014-01-07 25            14            682.9     682.4
190 20260310 2012-01-07  3             0            178.8     178.8
191 20260310 2012-01-07  5             0            263.2     263.2
192 20260310 2012-01-07 10             1            454.1     453.9
193 20260310 2012-01-07 13             4            530.4     529.9
194 20260310 2012-01-07 15             6            575.9     575.5
195 20260310 2012-01-07 20            11            673.1     672.5
196 20260310 2012-01-07 25            16            746.7     745.3
197 20260310 2013-01-07  3             0            178.8     178.8
198 20260310 2013-01-07  5             0            269.8     269.8
199 20260310 2013-01-07 10             0            472.4     472.4
200 20260310 2013-01-07 13             3            541.4     541.2
201 20260310 2013-01-07 15             5            585.9     586.1
202 20260310 2013-01-07 20            10            682.3     682.6
203 20260310 2013-01-07 25            15            756.5     755.9
204 20260310 2014-01-07  3             0            104.9     104.9
205 20260310 2014-01-07  5             0            196.5     196.5
206 20260310 2014-01-07 10             0            392.2     392.2
207 20260310 2014-01-07 13             2            471.3     471.1
208 20260310 2014-01-07 15             4            516.3     515.8
209 20260310 2014-01-07 20             9            612.9     611.4
210 20260310 2014-01-07 25            14            686.2     684.5
    delta_lower delta_rel_lower abs_delta_rel_lower ref_upper ext_upper
1    0.0         0.000000       0.000000            235.2     235.2
2    0.0         0.000000       0.000000            330.8     330.8
3    0.0         0.000000       0.000000            562.6     562.0
4   -0.6        -0.001132       0.001132            666.8     666.4
5   -0.2        -0.000348       0.000348            727.1     726.5
6   -1.2        -0.001789       0.001789            854.3     855.6
7    0.4         0.000538       0.000538            958.4     959.2
8    0.0         0.000000       0.000000            235.2     235.2
9    0.0         0.000000       0.000000            338.2     338.2
10   0.0         0.000000       0.000000            561.6     561.6
11   0.2         0.000370       0.000370            672.1     672.0
12   0.4         0.000684       0.000684            732.2     732.4
13   0.0         0.000000       0.000000            860.1     862.6
14   2.1         0.002794       0.002794            963.8     965.8
15   0.0         0.000000       0.000000            149.1     149.1
16   0.0         0.000000       0.000000            255.5     255.5
17   0.0         0.000000       0.000000            473.8     473.8
18  -0.5        -0.001060       0.001060            589.3     588.7
19  -0.7        -0.001357       0.001357            650.2     649.9
20  -2.4        -0.003927       0.003927            778.1     780.2
21  -0.7        -0.001024       0.001024            882.0     883.6
22   0.0         0.000000       0.000000            235.2     235.2
23   0.0         0.000000       0.000000            330.8     330.8
24  -0.4        -0.000880       0.000880            562.6     562.8
25  -0.5        -0.000943       0.000943            666.7     666.3
26   0.3         0.000523       0.000523            727.4     726.5
27   0.6         0.000897       0.000897            855.3     854.8
28   1.2         0.001616       0.001616            958.8     959.5
29   0.0         0.000000       0.000000            235.2     235.2
30   0.0         0.000000       0.000000            338.2     338.2
⋮   ⋮           ⋮               ⋮                   ⋮         ⋮
181  0.4         0.000588       0.000588            859.9     860.5
182 -0.5        -0.000663       0.000663            964.1     964.5
183  0.0         0.000000       0.000000            149.1     149.1
184  0.0         0.000000       0.000000            255.5     255.5
185  0.0         0.000000       0.000000            473.8     473.8
186 -1.0        -0.002118       0.002118            588.0     588.8
187 -0.4        -0.000774       0.000774            649.5     649.2
188  0.6         0.000984       0.000984            779.8     778.4
189 -0.5        -0.000732       0.000732            884.0     882.4
190  0.0         0.000000       0.000000            235.2     235.2
191  0.0         0.000000       0.000000            330.8     330.8
192 -0.2        -0.000440       0.000440            562.5     563.3
193 -0.5        -0.000943       0.000943            664.9     666.9
194 -0.4        -0.000695       0.000695            724.8     726.9
195 -0.6        -0.000891       0.000891            853.0     855.4
196 -1.4        -0.001875       0.001875            956.9     960.2
197  0.0         0.000000       0.000000            235.2     235.2
198  0.0         0.000000       0.000000            338.2     338.2
199  0.0         0.000000       0.000000            561.6     561.6
200 -0.2        -0.000369       0.000369            671.1     673.1
201  0.2         0.000341       0.000341            731.5     733.5
202  0.3         0.000440       0.000440            860.0     862.2
203 -0.6        -0.000793       0.000793            963.8     967.3
204  0.0         0.000000       0.000000            149.1     149.1
205  0.0         0.000000       0.000000            255.5     255.5
206  0.0         0.000000       0.000000            473.8     473.8
207 -0.2        -0.000424       0.000424            588.5     589.8
208 -0.5        -0.000968       0.000968            649.0     650.7
209 -1.5        -0.002447       0.002447            777.6     780.0
210 -1.7        -0.002477       0.002477            881.9     885.9
    delta_upper delta_rel_upper abs_delta_rel_upper
1    0.0         0.000000       0.000000
2    0.0         0.000000       0.000000
3   -0.6        -0.001066       0.001066
4   -0.4        -0.000600       0.000600
5   -0.6        -0.000825       0.000825
6    1.3         0.001522       0.001522
7    0.8         0.000835       0.000835
8    0.0         0.000000       0.000000
9    0.0         0.000000       0.000000
10   0.0         0.000000       0.000000
11  -0.1        -0.000149       0.000149
12   0.2         0.000273       0.000273
13   2.5         0.002907       0.002907
14   2.0         0.002075       0.002075
15   0.0         0.000000       0.000000
16   0.0         0.000000       0.000000
17   0.0         0.000000       0.000000
18  -0.6        -0.001018       0.001018
19  -0.3        -0.000461       0.000461
20   2.1         0.002699       0.002699
21   1.6         0.001814       0.001814
22   0.0         0.000000       0.000000
23   0.0         0.000000       0.000000
24   0.2         0.000355       0.000355
25  -0.4        -0.000600       0.000600
26  -0.9        -0.001237       0.001237
27  -0.5        -0.000585       0.000585
28   0.7         0.000730       0.000730
29   0.0         0.000000       0.000000
30   0.0         0.000000       0.000000
⋮   ⋮           ⋮               ⋮
181  0.6         0.000698       0.000698
182  0.4         0.000415       0.000415
183  0.0         0.000000       0.000000
184  0.0         0.000000       0.000000
185  0.0         0.000000       0.000000
186  0.8         0.001361       0.001361
187 -0.3        -0.000462       0.000462
188 -1.4        -0.001795       0.001795
189 -1.6        -0.001810       0.001810
190  0.0         0.000000       0.000000
191  0.0         0.000000       0.000000
192  0.8         0.001422       0.001422
193  2.0         0.003008       0.003008
194  2.1         0.002897       0.002897
195  2.4         0.002814       0.002814
196  3.3         0.003449       0.003449
197  0.0         0.000000       0.000000
198  0.0         0.000000       0.000000
199  0.0         0.000000       0.000000
200  2.0         0.002980       0.002980
201  2.0         0.002734       0.002734
202  2.2         0.002558       0.002558
203  3.5         0.003631       0.003631
204  0.0         0.000000       0.000000
205  0.0         0.000000       0.000000
206  0.0         0.000000       0.000000
207  1.3         0.002209       0.002209
208  1.7         0.002619       0.002619
209  2.4         0.003086       0.003086
210  4.0         0.004536       0.004536

#### 8. Különbségek összefoglalása

Az alábbi összesítő táblázat a seedek mentén előállított összehasonlító táblák (`compare_all`) alapján, indexdátumonként és horizontonként a relatív eltérés (`|delta_rel|`) leíró statisztikáit adja meg.

- A sorok egy-egy indexdátum–horizont párt jelentenek.
- Az oszlopok a seed-választásból adódó ingadozás mértékét írják le (`min`, `max`, `median`, `mean`, `sd`), valamint megjelenítik a küszöböket és a hozzájuk tartozó megfelelést.
- A `sim_inc_years` oszlop azt mutatja, hogy az adott indexdátum–horizont párhoz a `registry_start_date`-ig hány évnyi incidenciát kell szimulálni (0, ha a teljes időablak a regiszteridőszakon belül van).

Ez a táblázat közvetlen viszonyítási alapot ad annak megítéléséhez, hogy a referencia és a kiterjesztett megoldás közötti eltérés nagyságrendje mennyiben illeszkedik a seed-függő változékonyság tartományába.

In [9]:
# Összefoglalás: |delta| leíró statisztikák seedek mentén

cmp <- data.table::as.data.table(compare_all)

if (!"abs_delta_rel" %in% names(cmp)) {
  cmp[, delta_rel := (ext - ref) / ref]
  cmp[, abs_delta_rel := abs(delta_rel)]
}

summary_abs_delta <- cmp[
  , .(
    ref = {
      v <- ref[seed == seeds[1]]
      if (length(v) == 0) v <- ref
      as.numeric(v[1])
    },
    sim_inc_years = {
      idx_d <- as.Date(index_date[1])
      start_d <- idx_d - round(horizon_years[1] * 365.25)
      yrs_need <- as.numeric(difftime(registry_start_date, start_d, units = "days")) / 365.25
      as.integer(round(pmax(0, pmin(horizon_years[1], yrs_need))))
    },
    abs_delta_rel_min = min(abs_delta_rel, na.rm = TRUE),
    abs_delta_rel_max = max(abs_delta_rel, na.rm = TRUE),
    abs_delta_rel_med = stats::median(abs_delta_rel, na.rm = TRUE),
    abs_delta_rel_mean = mean(abs_delta_rel, na.rm = TRUE),
    abs_delta_rel_sd = stats::sd(abs_delta_rel, na.rm = TRUE)
  ),
  by = .(index_date, horizon_years)
]

summary_abs_delta <- summary_abs_delta[order(as.Date(index_date), horizon_years)]
summary_abs_delta <- summary_abs_delta[, c(
  "index_date", "horizon_years", "sim_inc_years", "ref",
  "abs_delta_rel_min", "abs_delta_rel_max", "abs_delta_rel_med", "abs_delta_rel_mean", "abs_delta_rel_sd"
), with = FALSE]

summary_abs_delta[, `:=`(
  ref = round(ref, 2),
  sim_inc_years = as.integer(sim_inc_years),
  abs_delta_rel_min = round(abs_delta_rel_min, 6),
  abs_delta_rel_max = round(abs_delta_rel_max, 6),
  abs_delta_rel_med = round(abs_delta_rel_med, 6),
  abs_delta_rel_mean = round(abs_delta_rel_mean, 6),
  abs_delta_rel_sd = round(abs_delta_rel_sd, 6)
)]

summary_abs_delta

   index_date horizon_years sim_inc_years ref    abs_delta_rel_min
1  2012-01-07  3             0            207.00 0.000000
2  2012-01-07  5             0            297.00 0.000000
3  2012-01-07 10             1            508.35 0.000000
4  2012-01-07 13             4            598.35 0.000084
5  2012-01-07 15             6            650.83 0.000246
6  2012-01-07 20            11            762.57 0.000053
7  2012-01-07 25            16            850.63 0.000224
8  2013-01-07  3             0            207.00 0.000000
9  2013-01-07  5             0            304.00 0.000000
10 2013-01-07 10             0            517.00 0.000000
11 2013-01-07 13             3            606.37 0.000033
12 2013-01-07 15             5            658.48 0.000122
13 2013-01-07 20            10            769.78 0.000104
14 2013-01-07 25            15            857.76 0.000047
15 2014-01-07  3             0            127.00 0.000000
16 2014-01-07  5             0            226.00 0.000000
17 2014-01-07 10             0            433.00 0.000000
18 2014-01-07 13             2            530.41 0.000057
19 2014-01-07 15             4            582.96 0.000189
20 2014-01-07 20             9            694.63 0.000072
21 2014-01-07 25            14            782.69 0.000345
   abs_delta_rel_max abs_delta_rel_med abs_delta_rel_mean abs_delta_rel_sd
1  0.000000          0.000000          0.000000           0.000000
2  0.000000          0.000000          0.000000           0.000000
3  0.000748          0.000207          0.000301           0.000263
4  0.001523          0.000527          0.000628           0.000508
5  0.002557          0.000530          0.000815           0.000686
6  0.002393          0.000945          0.000922           0.000848
7  0.002972          0.001116          0.001159           0.000788
8  0.000000          0.000000          0.000000           0.000000
9  0.000000          0.000000          0.000000           0.000000
10 0.000000          0.000000          0.000000           0.000000
11 0.001468          0.000585          0.000589           0.000492
12 0.001716          0.000842          0.000821           0.000493
13 0.001868          0.001272          0.001134           0.000599
14 0.002965          0.001309          0.001241           0.001010
15 0.000000          0.000000          0.000000           0.000000
16 0.000000          0.000000          0.000000           0.000000
17 0.000000          0.000000          0.000000           0.000000
18 0.001265          0.000462          0.000528           0.000419
19 0.001702          0.000583          0.000683           0.000479
20 0.002049          0.000870          0.000932           0.000694
21 0.003394          0.001194          0.001317           0.000908

### 9. Összesítés (egyezési kritériumok)

Az alábbi összefoglaló táblák a bevezetőben és a dolgozat validálási kritériumai között rögzített relatív eltérésre épülnek. A pontbecslésre és a konfidencia-intervallumok határaira rendre:

- `delta_P = (P_ext - P_ref) / P_ref`,
- `delta_q = (q_ext - q_ref) / q_ref`, `alpha` értékekre `0.025` és `0.975`.

Az egyezést a rácson és seedenként képzett `|delta|` eltérések maximális és átlagos értékei alapján értékeljük. A küszöbök: `epsilon_max = 1e-2` a maximális eltérésre, illetve `epsilon_mean = 1e-3` az átlagos eltérésre.

In [10]:
# Összesítés: relatív eltérések (pontbecslés és intervallumhatárok)
epsilon_max <- 1e-2
epsilon_mean <- 1e-3

stopifnot(exists("compare_all"), exists("compare_ci_all"))

# 1) Pontbecslések: |delta_P|
cmp_est <- data.table::as.data.table(compare_all)
cmp_est[, delta_rel := ifelse(ref == 0, NA_real_, (ext - ref) / ref)]
cmp_est[, abs_delta_rel := abs(delta_rel)]

aggregate_abs_delta <- function(dt, case_label, by_cols = NULL) {
  if (is.null(by_cols) || length(by_cols) == 0) {
    out <- dt[, .(
      abs_delta_rel_max = max(abs_delta_rel, na.rm = TRUE),
      abs_delta_rel_mean = mean(abs_delta_rel, na.rm = TRUE),
      epsilon_max = epsilon_max,
      epsilon_mean = epsilon_mean
    )]
  } else {
    out <- dt[, .(
      abs_delta_rel_max = max(abs_delta_rel, na.rm = TRUE),
      abs_delta_rel_mean = mean(abs_delta_rel, na.rm = TRUE),
      epsilon_max = epsilon_max,
      epsilon_mean = epsilon_mean
    ), by = by_cols]
  }
  out[, case := case_label]
  out
}

summary_est <- data.table::rbindlist(list(
  aggregate_abs_delta(cmp_est, case_label = "all"),
  aggregate_abs_delta(cmp_est[as.integer(sim_inc_years) == 10], case_label = "sim_inc_years_int10")
), use.names = TRUE, fill = TRUE)
summary_est <- summary_est[order(case)]
summary_est[, `:=`(
  eps_ok_max = abs_delta_rel_max <= epsilon_max,
  eps_ok_mean = abs_delta_rel_mean <= epsilon_mean,
  eps_ok = (abs_delta_rel_max <= epsilon_max) & (abs_delta_rel_mean <= epsilon_mean)
)]

summary_est[, `:=`(
  abs_delta_rel_max = round(abs_delta_rel_max, 6),
  abs_delta_rel_mean = round(abs_delta_rel_mean, 6)
)]

# 2) Intervallumhatárok: |delta_q,alpha| (alpha = 0.025, 0.975)
cmp_ci <- data.table::as.data.table(compare_ci_all)
cmp_ci[, delta_rel_lower := ifelse(ref_lower == 0, NA_real_, (ext_lower - ref_lower) / ref_lower)]
cmp_ci[, delta_rel_upper := ifelse(ref_upper == 0, NA_real_, (ext_upper - ref_upper) / ref_upper)]

ci_long <- data.table::rbindlist(list(
  cmp_ci[, .(alpha = 0.025, abs_delta_rel = abs(delta_rel_lower), sim_inc_years = as.integer(sim_inc_years))],
  cmp_ci[, .(alpha = 0.975, abs_delta_rel = abs(delta_rel_upper), sim_inc_years = as.integer(sim_inc_years))]
), use.names = TRUE, fill = TRUE)

summary_ci <- data.table::rbindlist(list(
  aggregate_abs_delta(ci_long, case_label = "all", by_cols = "alpha"),
  aggregate_abs_delta(ci_long[as.integer(sim_inc_years) == 10], case_label = "sim_inc_years_int10", by_cols = "alpha")
), use.names = TRUE, fill = TRUE)
summary_ci <- summary_ci[order(alpha, case)]
summary_ci[, `:=`(
  eps_ok_max = abs_delta_rel_max <= epsilon_max,
  eps_ok_mean = abs_delta_rel_mean <= epsilon_mean,
  eps_ok = (abs_delta_rel_max <= epsilon_max) & (abs_delta_rel_mean <= epsilon_mean)
)]

summary_ci[, `:=`(
  abs_delta_rel_max = round(abs_delta_rel_max, 6),
  abs_delta_rel_mean = round(abs_delta_rel_mean, 6)
)]

summary_est
summary_ci

  abs_delta_rel_max abs_delta_rel_mean epsilon_max epsilon_mean
1 0.003394          0.000527           0.01        0.001
2 0.001868          0.001134           0.01        0.001
  case                eps_ok_max eps_ok_mean eps_ok
1 all                 TRUE        TRUE        TRUE
2 sim_inc_years_int10 TRUE       FALSE       FALSE

  alpha abs_delta_rel_max abs_delta_rel_mean epsilon_max epsilon_mean
1 0.025 0.006299          0.001035           0.01        0.001
2 0.025 0.002494          0.001204           0.01        0.001
3 0.975 0.006154          0.001030           0.01        0.001
4 0.975 0.003598          0.001732           0.01        0.001
  case                eps_ok_max eps_ok_mean eps_ok
1 all                 TRUE       FALSE       FALSE
2 sim_inc_years_int10 TRUE       FALSE       FALSE
3 all                 TRUE       FALSE       FALSE
4 sim_inc_years_int10 TRUE       FALSE       FALSE

### 10. Megállapítás

A fenti prefix-tábla oszlopaiban ugyanazt az eljárást futtatjuk eltérő horizontkészletekkel (a `num_years` vektor prefixeivel), miközben minden futtatás előtt ugyanazt a véletlenszám-generátor magot (seedet) állítjuk be. Ennek ellenére a közös horizontokra kapott becslések nem feltétlenül egyeznek, mert a horizontkészlet megváltoztatása a szimuláció teljes lefutását is megváltoztatja.

A fő ok a véletlenszám-felhasználás eltérő ütemezése és mennyisége:

- A `prevalence()` a szimuláció induló dátumát a **legnagyobb kért horizont** alapján állítja be: `sim_start_date <- min(index_dates) - years(max(num_years_to_estimate))` (R/prevalence.R). Ha a horizontlistát bővítjük, a `sim_start_date` korábbra kerül.
- A `sim_prevalence()` ezután a szimulációs ablak hosszát a `starting_date` és a legkésőbbi indexdátum különbségéből számolja: `number_incident_days <- difftime(max(index_dates), starting_date, ...)` (R/prevalence.R). A hosszabb ablak **más (és tipikusan több) szimulált incidens esetet** eredményezhet a `draw_incident_population(...)` hívásban, ami a véletlenszám-generátor állapotát is másképp "fogyasztja".
- A kiterjesztett Monte Carlo magban futásonként egyszer sorsolunk esetszintű küszöböt: `xi <- runif(nrow(incident_population))`, majd ezt az összes indexdátumhoz felhasználjuk: `alive_k <- I(xi <= p_k)` (R/prevalence.R). Ha a szimulált incidens populáció mérete (és így a `xi` hossza) megváltozik, akkor ugyanazon kezdő seed mellett is eltérő RNG-állapotból folytatódnak a további lépések.

A referencia megoldáshoz képest a kiterjesztés a státuszképzés véletlen komponensét is másképp szervezi: a túlélési valószínűségekhez tartozó bináris státusz nem független Bernoulli-sorsolások sorozataként áll elő, hanem az esetszintű `xi ~ Unif(0,1)` küszöb és a `p_k` túlélési valószínűségek összehasonlításával. Ez azonos seed használat mellett is megváltoztatja a véletlenszám-hívások mintázatát, ezért ugyanazon véletlenmag mellett sem várható szigorú numerikus egyezés.

Módszertani szempontból a kiterjesztés célja az, hogy **egy futáson belül** az indexdátumok mentén időben konzisztens státuszképzés történjen (dolgozat 5. fejezet: esetszintű `xi` küszöb és a Delta-mátrix/maszk konstrukció). Ez a tulajdonság nem garantálja, hogy **külön futtatások** (eltérő horizontkészletek) között a közös horizontokra kapott becslések változatlanok maradnak.

Gyakorlati értelmezés: a prefix-oszlopok közötti különbség lényegében azt jelenti, hogy a közös horizont becslése egy másik (ugyanazzal a maggal indított, de másképp felhasznált) véletlenszám-sorozaton alapul. Emiatt a különbségek nagyságrendje tipikusan összemérhető azzal a variabilitással, amit különböző seed-beállítások is okoznának.

További megállapítás a teljes notebook alapján: a seedek mentén képzett összevető táblák összesítése (az indexdátum–horizont párokhoz tartozó `|delta|` leíró statisztikái; lásd az "Összefoglalás (seed-variabilitás az eltérésben)" táblázatot, `summary_abs_delta`) azt mutatja, hogy a referencia és a kiterjesztett becslések közötti eltérések nagyságrendje a vizsgált beállítások mellett jellemzően a seed-választásból adódó Monte Carlo változékonysággal összemérhető. A különbségek előjele seed szerint is változhat, és az indexdátumok mentén nem rajzolódik ki tartós, egyirányú eltolódás; ez összhangban áll azzal, hogy a megfigyelt eltérések elsődleges forrása a futási szerkezet és a véletlenszám-felhasználás ütemezésének különbsége.

Mindezek alapján a kiterjesztett eljárás által adott becslések a referencia-megoldás eredményeivel **összevethetők**, és a megfigyelt eltérések a vizsgált beállítások mellett **módszertanilag elfogadható mértékűeknek** tekinthetők. Ennek megfelelően a kiterjesztett implementáció a referencia-eljárás logikájával **konzisztens** kimenetet szolgáltat, és a több indexdátum együttes kezelésére vonatkozó kiterjesztés validáltnak tekinthető a jelen vizsgálati keretben.

# todo
1. a kiértékelő táblákat erre a epsilon alapú különbségkre kell átvariálni
2. a konfidencia intervallumokat ugyanígy ki kell értékelni
3. Meg kell vizsgálni, hogy konvergál-e a nullához, ha növelem az ismétlésszámot
4. Ennek fényében átírni a megállapításokat